[project]
name = "python-cs50"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "cowsay>=6.1",
    "fastapi>=0.116.1",
    "pillow>=11.3.0",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
